Refactor navigation drawer and support/add various navigation items
Crystal-Creations-GbR/crystal-components pull request #65
Opened 2024-03-26 15:28 UTC by ItsPierre

2024-03-26 21:23 UTC, ItsPierre commented
https://github.com/Crystal-Creations-GbR/crystal-components/compare/5d1f458625f0c79aad12a6b2377ea2935134aa4a..d29ad43ecfa1e0ed3eba5f8d84d73a26dc9e2de7


Made it smaller and the text not bold

2024-03-26 21:31 UTC, johannes-huther requested changes

2024-03-26 21:31 UTC, johannes-huther commented on src/components/NavigationDrawer/CNavigationDrawer.vue
please use kebab case for the directory

2024-03-26 21:31 UTC, johannes-huther commented on src/components/NavigationDrawer/CNavigationSubtitle.vue
> +
this belongs to the first commit, doesn't it?

2024-03-26 21:31 UTC, johannes-huther commented on src/components/NavigationDrawer/CNavigationSubtitle.vue
> +// When used in navigation drawer, show it on rail mode
Do you mean hide?

2024-03-26 22:39 UTC, ItsPierre commented on src/components/NavigationDrawer/CNavigationDrawer.vue
just took 40 minutes to rebase...

2024-03-26 22:39 UTC, ItsPierre commented
https://github.com/Crystal-Creations-GbR/crystal-components/compare/d29ad43ecfa1e0ed3eba5f8d84d73a26dc9e2de7..84b60a417144297bb0d11b356d5a779457503b37

2024-03-28 18:06 UTC, johannes-huther approved these changes

2024-03-28 18:06 UTC, merged